// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtIhdjUFhJBd8hMDoxTYbp58yIR6qXITc',
    appId: '1:855463628631:web:a88f5d309c7fc954c3b812',
    messagingSenderId: '855463628631',
    projectId: 'barber-162ce',
    authDomain: 'barber-162ce.firebaseapp.com',
    storageBucket: 'barber-162ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACmOxcmJTUUJrpEc3WzJVhsQpMUimxq6c',
    appId: '1:855463628631:android:cbd71f0a2cb14e42c3b812',
    messagingSenderId: '855463628631',
    projectId: 'barber-162ce',
    storageBucket: 'barber-162ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Z44kSHLRwLCF8RPqPauOCmrhgIv2x3A',
    appId: '1:855463628631:ios:50184bce66bbef35c3b812',
    messagingSenderId: '855463628631',
    projectId: 'barber-162ce',
    storageBucket: 'barber-162ce.firebasestorage.app',
    iosBundleId: 'com.example.barber',
  );
}
